- job:
    name: ceilometer-dsvm-tempest-plugin-mongodb
    parent: legacy-dsvm-base
    run: playbooks/legacy/ceilometer-dsvm-tempest-plugin-mongodb/run.yaml
    post-run: playbooks/legacy/ceilometer-dsvm-tempest-plugin-mongodb/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/ceilometer
      - openstack/tempest

- job:
    name: ceilometer-dsvm-tempest-plugin-mongodb-identity-v3-only
    parent: legacy-dsvm-base
    run: playbooks/legacy/ceilometer-dsvm-tempest-plugin-mongodb-identity-v3-only/run.yaml
    post-run: playbooks/legacy/ceilometer-dsvm-tempest-plugin-mongodb-identity-v3-only/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/ceilometer
      - openstack/tempest

- job:
    name: ceilometer-dsvm-tempest-plugin-mysql
    parent: legacy-dsvm-base
    run: playbooks/legacy/ceilometer-dsvm-tempest-plugin-mysql/run.yaml
    post-run: playbooks/legacy/ceilometer-dsvm-tempest-plugin-mysql/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/ceilometer
      - openstack/tempest

- job:
    name: ceilometer-tox-py27-mongodb
    parent: legacy-base
    run: playbooks/legacy/ceilometer-tox-py27-mongodb/run.yaml
    post-run: playbooks/legacy/ceilometer-tox-py27-mongodb/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: ceilometer-tox-py27-mysql
    parent: legacy-base
    run: playbooks/legacy/ceilometer-tox-py27-mysql/run.yaml
    post-run: playbooks/legacy/ceilometer-tox-py27-mysql/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: ceilometer-tox-py27-postgresql
    parent: legacy-base
    run: playbooks/legacy/ceilometer-tox-py27-postgresql/run.yaml
    post-run: playbooks/legacy/ceilometer-tox-py27-postgresql/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: grenade-dsvm-ceilometer
    parent: legacy-dsvm-base
    run: playbooks/legacy/grenade-dsvm-ceilometer/run.yaml
    post-run: playbooks/legacy/grenade-dsvm-ceilometer/post.yaml
    timeout: 10800
    required-projects:
      - openstack-dev/grenade
      - openstack-infra/devstack-gate
      - openstack/ceilometer

- job:
    name: telemetry-dsvm-integration-ceilometer
    parent: legacy-dsvm-base
    run: playbooks/legacy/telemetry-dsvm-integration-ceilometer/run.yaml
    post-run: playbooks/legacy/telemetry-dsvm-integration-ceilometer/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/aodh
      - openstack/ceilometer
      - openstack/panko
      # following are required when DEVSTACK_GATE_HEAT, which this
      # job turns on
      - openstack/dib-utils
      - openstack/diskimage-builder

- project:
    name: openstack/ceilometer
    check:
      jobs:
        - ceilometer-dsvm-tempest-plugin-mongodb
        - ceilometer-dsvm-tempest-plugin-mysql
        - ceilometer-tox-py27-mongodb
        - ceilometer-tox-py27-mysql
        - ceilometer-tox-py27-postgresql
        - grenade-dsvm-ceilometer:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - telemetry-dsvm-integration-ceilometer
        - ceilometer-dsvm-tempest-plugin-mongodb-identity-v3-only
    gate:
      jobs:
        - ceilometer-dsvm-tempest-plugin-mongodb
        - ceilometer-dsvm-tempest-plugin-mysql
        - ceilometer-tox-py27-mongodb
        - ceilometer-tox-py27-mysql
        - ceilometer-tox-py27-postgresql
        - grenade-dsvm-ceilometer:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - telemetry-dsvm-integration-ceilometer
        - ceilometer-dsvm-tempest-plugin-mongodb-identity-v3-only
