#!/usr/bin/python2
#
# Copyright 2017 NeCTAR
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# To set up replicated notifications:
# /etc/ceilometer/event_pipeline.yaml and /etc/ceilometer/pipeline.yaml:
# sinks:
#     - name: some_sink
#       publishers:
#           - notifier://?topic=<topic-name>
#
# run this script as:
# q_process <topic-name> --config-file /etc/ceilometer/ceilometer.conf

import sys

from ceilometer.cmd.queue_process import main

if __name__ == '__main__':
    if len(sys.argv) == 1:
        raise Exception("Topic not specified")
    topic = sys.argv[1]
    del sys.argv[1]
    main(topic)
