#!/bin/bash
#---------------------------
# Testing ceilometer-daemons
#---------------------------
set -e
DAEMONS=('ceilometer-agent-notification'
         'ceilometer-alarm-evaluator'
         'ceilometer-alarm-notifier'
         'ceilometer-api'
         'ceilometer-collector'
         'ceilometer-polling')

for daemon in "${DAEMONS[@]}"; do
    if pidof -x $daemon > /dev/null; then
        echo "OK"
    else
        echo "ERROR: ${daemon} IS NOT RUNNING"
        exit 1
    fi
done
