#!/bin/bash
#----------------------------
# Testing ceilometer services
#----------------------------
set -e
SERVICES=('ceilometer-agent-central'
          'ceilometer-agent-compute'
          'ceilometer-agent-ipmi'
          'ceilometer-agent-notification'
          'ceilometer-api'
          'ceilometer-collector'
          'ceilometer-polling')

for service in "${SERVICES[@]}"; do
    if systemctl is-active $service > /dev/null; then
        echo "OK"
    else
        echo "ERROR: ${service} IS NOT RUNNING"
        exit 1
    fi
done
